### ISSUE TITLE
TypeError: add_mesh_with_normals(): incompatible function arguments. 

### ISSUE THREAD

**Issue by Bartender-bit** [zhengyanzhao1997/COOP#1]
when I running the command:"python infer/infer.py --rh-work-dir ../model/Hnet/ --body-work-dir ../model/Bnet/  --data-file ../data --save-file ./output",I got an error on:

```
Traceback (most recent call last):
  File "infer/infer.py", line 597, in <module>
    inference()
  File "infer/infer.py", line 594, in inference
    tester.inference_generate_difheight()
  File "infer/infer.py", line 497, in inference_generate_difheight
    sp_anim.add_frame([sbj_opt, obj_i, grnd_mesh], ['refined_grasp' , 'object', 'ground_mesh'])
  File "/home/COOP/src/./tools/vis_tools.py", line 122, in add_frame
    meshes_list = self.meshes_to_sp(meshes_list_ps, layer_names)
  File "/home/COOP/src/./tools/vis_tools.py", line 113, in meshes_to_sp
    sp_m.add_mesh_with_normals(**params)
TypeError: add_mesh_with_normals(): incompatible function arguments. The following argument types are supported:
    1. (self: scenepic._scenepic.Mesh, vertices: numpy.ndarray[numpy.float32[m, 3], flags.c_contiguous], normals: numpy.ndarray[numpy.float32[m, 3], flags.c_contiguous], triangles: numpy.ndarray[numpy.uint32[m, 3], flags.c_contiguous], colors: numpy.ndarray[numpy.float32[m, 3], flags.c_contiguous] = array([], shape=(0, 3), dtype=float32), uvs: numpy.ndarray[numpy.float32[m, 2], flags.c_contiguous] = array([], shape=(0, 2), dtype=float32), transform: numpy.ndarray[numpy.float32[4, 4]] = array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32), reverse_triangle_order: bool = False, fill_triangles: bool = True, add_wireframe: bool = False) -> None

Invoked with: {
	"CameraSpace": false,
	"CommandType": "DefineMesh",
	"Definition": 
	{
		"IndexBufferType": "UInt16",
		"LineBuffer": "eAEDAAAAAAEAAAAAAg==",
		"PrimitiveType": "MultiColorMesh",
		"TriangleBuffer": "eAEDAAAAAAEAAAAAAw==",
		"VertexBuffer": "eAEDAAAAAAEAAAAACQ=="
	},
	"DoubleSided": false,
	"IsBillboard": false,
	"IsLabel": false,
	"LayerId": "refined_grasp",
	"MeshId": "Mesh-0"
}
; kwargs: vertices=array([[0.44230837, 1.0971206 , 0.3596604 ],
       [0.44325614, 1.0945121 , 0.35644534],
       [0.4434521 , 1.095121  , 0.35589513],
       ...,
       [0.38949513, 1.0904846 , 0.45990646],
       [0.3914864 , 1.0903082 , 0.4584813 ],
       [0.39337057, 1.0896556 , 0.45705187]], dtype=float32), normals=array([[ 6.25814497e-01,  2.93365091e-01, -7.22698510e-01],
       [ 4.39332932e-01,  7.25375473e-01, -5.29921710e-01],
       [ 1.28836408e-02,  7.89259493e-01, -6.13924682e-01],
       ...,
       [ 6.37919605e-02,  9.91782010e-01,  1.10900909e-01],
       [ 1.90891072e-01,  9.81610715e-01,  9.88925924e-04],
       [ 3.31399858e-01,  9.37713981e-01, -1.04243316e-01]], dtype=float32), triangles=array([[    3,     1,     0],
       [    7,     5,     4],
       [   12,    14,    13],
       ...,
       [ 9944, 10097, 10084],
       [ 9940, 10084, 10071],
       [10071, 10058,  9932]], dtype=uint32), colors=array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]], dtype=float32)

```

Doese anyone know how to solve it?

**Comment by mengqing0312** [comment]
请问这个问题你解决了吗
